apiVersion: v1
kind: PersistentVolume
metadata: 
 name: mysql-persistent-storage
spec: 
 capacity: 
   storage: 20Gi
 hostPath:
  path: /tmp/data
  type: DirectoryOrCreate
 accessModes:
 - ReadWriteOnce
