apiVersion: v1
kind: PersistentVolume
metadata: 
 name: wordpress-persistent-storage
spec: 
 capacity: 
   storage: 1Gi
 hostPath:
  path: /tmp/data
  type: DirectoryOrCreate
 accessModes:
 - ReadWriteOnce