apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ben-podadmin-binding
  namespace: default
subjects:
- kind: User
  name: ben
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-admin
  apiGroup: rbac.authorization.k8s.io
