apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata: 
 name: ben-csr
spec: 
 groups: 
 - "system:authenticated"
 usages: 
 - client auth
 - digital signature
 - key encipherment
 signerName: kubernetes.io/kube-apiserver-client
 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RZbVZ1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBc1RHZGw4RHdIbEZzUWNDWGVpZjN2VDNjYTkxOE9TNzIwaXloWGlOcXlJcDR0L0xGCm5pTHNCZmFxa2ZGSXF6MTRldXRLZXNwUzhBdGpCVU1JeUxWc2VXc1JyNGRWM3FJdFdWS0E0dzRKM1ZYTWxDSmgKUGZjZFVRTTVlUlFsQzhYa2U0dGJrdDZZb1JuTE41aDJvOFJRc2h2QTlBdTZvUnMvTnk2Z1huOTBncFc5OVh5NgpsT3dtODRSVXBYQ2N4T3JuWHQydEZxdXcwWWxmeEdRMXVJVVh2WEQyVVNzZG4remZDWklYbE11VGJ1ZHkwNlZnCjhKTWc4YW1LL0ZndldEUFltZGpoMVc4dnRoQWEyS1JkMjFqUytoUzBQcHRYdHUvVkU0dEVIWThPK3U5ZEpkNzQKZEpFTllacVJVSXJHOE1GS3RMaHR0NG5Vanh2Qnh5TWcrcGpBbndJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFJSlB0a3k3dnZCU1hvaVhkZEFCUXlnTVIxYmVhUERtZEx6VmUyYVBxTmxtMjlBdWpyT2xWT2xuCmRDMkJzYTJOUVBSWWZsb1ZqRjBzT2k2T3FPbk9JVnJqbWhXeVduL3dQTUJ1MEtQV0lFYmZpNW5HMkdCRThkbUYKQzJBZEN4S284eWd2Y01qZnIzcldsQ3dvTkV2bUpZUitXemN3T3gyT2J6RkJDQjlhT2wrc2NFM1Z2WW9QYnp5Two0ZEpWclJrMm0vUkI0ZTQvdjhjdnU3bExnYlUzSnZOZzNmZldaK0YvazZUTDhyaFd3STJSUHJmWitmd3hhdGg5CkVRd1I4UFBmZHRqZmVuTGlQbFBSL3M2TWdlbEtlK0ZHUyt0SFlobjkrbVRwd3YxZ0owcnlCUzF3OWQ1VnkrWXYKdmVVMmJvQVlCZEphcllja2pJQ1d1VFVlNmpTL1lZND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
